# Site settings
baseurl = "/"
title = "Sitting Duck Info"
paginate = 5
buildFuture = true
theme = "story"

[[menu.social]]
  name = "Twitter"
  title = "fab fa-twitter-square"
  url = "https://twitter.com/sittingduckinfo/"

[[menu.social]]
  name = "GitHub"
  title = "fab fa-github-square"
  url = "https://github.com/sitting-duck-info/"

[[menu.main]]
  name = "Talks"
  title = "Talks"
  url = "/talks/"

[[menu.main]]
  name = "Slides"
  title = "Slides"
  url = "/slides/"

[[menu.main]]
  name = "Archives"
  title = "Archives"
  url = "/archives/"

[[menu.main]]
  name = "About Us"
  title = "About Us"
  url = "/about-us/"

[params]
  author = "Sitting Duck Info"
  classes = []

[outputs]
  home = ["HTML", "JSON", "RSS"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML", "RSS"]
